# Generated by Django 3.2 on 2024-01-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(choices=[('Soğuk İçecekler', 'Soğuk İçecekler'), ('Sıcak İçecekler', 'Sıcak İçecekler'), ('Kahvaltılıklar', 'Kahvaltılıklar'), ('Burgerler', 'Burgerler'), ('Aparatifler', 'Aparatifler'), ('Tatlılar', 'Tatlılar'), ('Nargileler', 'Nargileler'), ('Kampanyalar', 'Kampanyalar')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
