# Generated by Django 3.2 on 2024-01-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katagori', models.CharField(choices=[('Soğuk İçecekler', 'Soğuk İçecekler'), ('Sıcak İçecekler', 'Sıcak İçecekler'), ('Kahvaltılıklar', 'Kahvaltılıklar'), ('Burgerler', 'Burgerler'), ('Aparatifler', 'Aparatifler'), ('Tatlılar', 'Tatlılar'), ('Nargileler', 'Nargileler'), ('Kampanyalar', 'Kampanyalar')], max_length=30)),
                ('urun_adi', models.CharField(max_length=255)),
                ('urun_icerigi', models.TextField(blank=True, null=True)),
                ('urun_fiyati', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
