# Generated by Django 3.2 on 2024-01-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240114_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urun',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='urunler',
        ),
    ]
