# Generated by Django 3.2 on 2024-01-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240114_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='katagori',
        ),
        migrations.RemoveField(
            model_name='product',
            name='urun_adi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='urun_fiyati',
        ),
        migrations.RemoveField(
            model_name='product',
            name='urun_icerigi',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Soğuk İçecekler', 'Soğuk İçecekler'), ('Sıcak İçecekler', 'Sıcak İçecekler'), ('Kahvaltılıklar', 'Kahvaltılıklar'), ('Burgerler', 'Burgerler'), (
                'Aparatifler', 'Aparatifler'), ('Tatlılar', 'Tatlılar'), ('Nargileler', 'Nargileler'), ('Kampanyalar', 'Kampanyalar')], default='Soğuk İçecekler', max_length=30, verbose_name='Kategorisi'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_content',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Ürünün İçeriği'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(
                default='Boş', max_length=255, verbose_name='Ürün Adı'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name='Ürünün Fiyarı'),
        ),
    ]
