# Generated by Django 3.2 on 2024-01-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240114_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name='Ürünün Fiyatı'),
        ),
    ]
