# Generated by Django 3.2 on 2024-01-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240114_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Katagori', 'verbose_name_plural': 'Katagoriler'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='catagory_name',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Katagori Adı'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='katagoriler',
        ),
    ]
