# Generated by Django 3.2 on 2024-01-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240114_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='catagory_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
