# Generated by Django 3.2 on 2024-01-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240123_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='category_id',
        ),
    ]
